export const RESET_TO = 'RESET_TO'
export const NAVIGATED_TO = 'NAVIGATED_TO'
export const NAVIGATED_TO_WITH_HISTORY = 'NAVIGATED_TO_WITH_HISTORY'
export const NAVIGATED_TO_WITH_HISTORY_NO_BACK_GESTURE = 'NAVIGATED_TO_WITH_HISTORY_NO_BACK_GESTURE'
export const NAVIGATED_BACK = 'NAVIGATED_BACK'

export const SIDE_MENU_GESTURES_ENABLED = 'SIDE_MENU_GESTURES_ENABLED'
export const SIDE_MENU_GESTURES_DISABLED = 'SIDE_MENU_GESTURES_DISABLED'
export const SIDE_MENU_TOGGLED = 'SIDE_MENU_TOGGLED'
export const SIDE_MENU_CLOSED = 'SIDE_MENU_CLOSED'
export const SIDE_MENU_OPENED = 'SIDE_MENU_OPENED'

export const SETTINGS_TOGGLE_LOADING = 'SETTINGS_TOGGLE_LOADING'
export const SETTINGS_TOGGLE_SUCCESS = 'SETTINGS_TOGGLE_SUCCESS'
export const SETTINGS_TOGGLE_ERROR = 'SETTINGS_TOGGLE_ERROR'

export const SENDBIRD_CONNECT = 'SENDBIRD_CONNECT'
export const SENDBIRD_CONNECT_ERROR = 'SENDBIRD_CONNECT_ERROR'
export const SENDBIRD_CONNECTED = 'SENDBIRD_CONNECTED'
export const SENDBIRD_SET_USER = 'SENDBIRD_SET_USER'

export const SENDBIRD_LIST_CHANNELS = 'SENDBIRD_LIST_CHANNELS'
export const SENDBIRD_LIST_CHANNELS_ERROR = 'SENDBIRD_LIST_CHANNELS_ERROR'
